import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./components/nav/Nav";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} max-w-[1920px] bg-green-50`}>
        <div className="min-h-screen flex flex-col max-w-7xl mx-auto bg-black">
          <Nav />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
